### ISSUE TITLE
is not an issue itself is more than a curiosity ok

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [brunurd/companion#26]
guys, supporters, people, please anyone can say to me which is the chromium version used on this browser it is because i love it and i love the fact that is lighter no matter that it is compatiible with a lot of google services (IT IS NOT AN ISSUE IF YOU ERASE IT IS FINE JUST I REQUEST ONE SINGLE THING THAT THE GUY WHICH DID POSSIBLE ALL THIS PROJECT OR THE TEAM ITSELF SEND ME AN EMAIL TO CONSIDER HIS CONTACT BECAUSE IT MUST BE GREAT)

**Comment by brunurd** [comment]
Hi, thanks @soyDESKTOP68A2MRFT by your appreciation.

currently this project is maintained only by me, but I accept any kind of contribution.  

The project uses electron as base, so for follow the chromium version you should check this electron doc: https://www.electronjs.org/docs/tutorial/electron-timelines

Currently the Companion uses the electron version 9.4.0 so the chromium version is M83 (it needs to be updated for sure).

I will not keep your issue, but I will open one for the electron update aside the chromium and to create a version label on the README file.

**Comment by brunurd** [comment]
this will be closed for the sake of those two new issues below:  
https://github.com/brunurd/companion/issues/27
https://github.com/brunurd/companion/issues/28
