### ISSUE TITLE
hello guys

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [brunurd/companion#30]
when i build with npm i don't get the program binaries  just get 2 .js files

**Comment by brunurd** [comment]
for generate the binaries you should run one of those `npm` commands, specific for your targeting platform:
```
dist:win
dist:linux
dist:mac
```
build is only to compile the final js files (sorry for the lack of documentation about that)

**Comment by soyDESKTOP68A2MRFT** [comment]
Thanks i have another question where are you from???? i say that because i
have family which has your lastname araujo from part of my paternal grandma
maybe we are cousins

**Comment by soyDESKTOP68A2MRFT** [comment]
another question is dist and the 2 dots or dist and an equal sign (=)

**Comment by brunurd** [comment]
I can't say the same for your name 😅 

I gonna close because the issue is resolved, ok?

but Araujo is a portuguese surname, is common there and in other portuguese speakers countries, like Brazil.

**Comment by soyDESKTOP68A2MRFT** [comment]
Thank you for the clarification.

**Comment by soyDESKTOP68A2MRFT** [comment]
And no it don't solved anything man i put the command on powershell and it
npm says me that the command doesn't exist but there is a command called
npm dist-tag but i don't know how to use it any suggestions

**Comment by brunurd** [comment]
@soyDESKTOP68A2MRFT sorry, probably you run `npm dist:linux`, but you should run `npm run dist:linux`, for example. Is that the case?
